---
- !ruby/object:Usergroup
  label_id: hatchup
  canonical_url: https://hatchup.herokuapp.com
  status: enabled
  default_locale: de
  country: Deutschland
  recurring: second wednesday
  email: hamburg@onruby.de
  twitter: HamburgOnRuby
  github_org: rughh
  github_repo: planning
  github_issue_template: 'meetup.md'
  organizers:
  - lindtdev
  - janz93
  - phoet
  location:
    :zoom: 12
    :lat: 53.56544
    :long: 9.95947
  default_time_zone: Europe/Berlin
  imprint:
    :address: |-
      Tigerstr. 32
      22525 Hamburg
    :contributors:
    - :name: Peter Schröder
      :email: phoetmail@googlemail.com
  tld: de
  coc: http://rubyberlin.github.io/code-of-conduct
